version: '3'

services:      
  catalogue:
    build: ./Catalogue
    ports:
      - "5200:5200"
    links:
       - db
  entry-point:
    build: ./entry-point 
    ports:
      - "5000:5000"
  db:
    build: ./db
    ports:
      - "27017:27017"

  search_log:
    build: ./Search_Log
    ports:
      - "5001:5001"

  notes:
    build: ./Notes
    ports:
      - "5300:5300"
